### ISSUE TITLE
Depend on release version of dhii/data-key-value-aware-interface

### ISSUE THREAD

**Issue by mecha** [Dhii/data-tree-interface#2]
This package depends on `dhii/data-key-value-aware-interface` with a version constraint of `dev-master`. [See here](https://github.com/Dhii/data-tree-interface/blob/develop/composer.json#L17).

Since that package has a `0.1` release, it is now recommended to depend on `^0.1`.

**Comment by XedinUnknown** [comment]
Done in d83de80fed6daab126619e0f3a80e51011192415.
